version: '3.1'

services:
  db:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: agendamento
      MYSQL_DATABASE: agendamento
      MYSQL_USER: agendamento
      MYSQL_PASSWORD: agendamento
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
